# 4.1 복구 가능성

## 4.1.1 복구 가능한 오류  

- 잘못된 사용자 입력  
- 네트워크 오류
- 중요하지 않은 작업 오류

일반적으로 시스템 외부의 무언가에 의해 야기되는 오류에 대해서는 대부분 시스템 전체가 표나지 않고 적절하게 처리하기 위해 노력해야 한다.  

> 오류 발생 시 stacktrace와 같이 내부 코드를 노출하면 안된다는 내용이라고 이해함  
> 서비스 로직에서 throw를 던지고, Spring @RestControllerAdvice, @ExceptionHandler를 사용하여 응답하는 편  

## 4.1.2 복구할 수 없는 오류

> 복구 가능한 오류와 복구할 수 없는 오류의 차이점을 이해하지 못 함  

## 4.1.3 호출하는 쪽에서만 오류 복구 가능 여부를 알 때가 많다.

- 오류로부터 복구하기를 호출하는 쪽에서 원하는가?
- 만약 그렇다면 오류를 처리할 필요가 있다는 것을 호출하는 쪽에서는 어떻게 알 수 있을까?
  
함수에 제공된 값으로 인해 발생하는 오류는 호출하는 쪽에서 복구하고자 하는 것으로 간주해야한다.  
- 함수가 어디서 호출될지 그리고 호출 시 제공되는 값이 어디서 올지 정확한 지식이 없다.
- 코드가 미래에 재사용될 가능성이 아주 희박하다. 재사용이 된다면 코드가 어디에서 호출되고 값이 어디서 오는지에 대한 가정이 의미가 없어질 수 있음을 뜻한다.  

> "코드가 미래에 재사용될 가능성이 아주 희박하다." 라는 문장 이해하지 못 함  

하지만 자신의 코드가 어떻게 사용되어야 하는지에 대해 스스로에게는 명백해 보일 수 있을지라도 다른 사람들에게는 분명하지 않을 수도 있다는 점을 이해해야 한다.  

> 테스트 코드로 케이스별 결과를 제공해야함  
> 메소드 명으로 메소드의 행위를 예상할 수 있어야 함  

```
fun isValid() {
    if (..) { throw }
    if (..) { throw }
}

이름이 isValid이기 때문에 호출부에서 코드를 읽을 때 Boolean을 리턴하는 함수로 착각할 수도 있을 것 같아요. 함수 이름 수정을 제안해 봅니다.  
isValidOrThrows라는 이름을 쓰는 것도 괜찮을 수 있겠습니다.  
한편, 코드를 읽는 사람이 Java - SpringBoot 개발 환경에 익숙한 사람이라고 전제한다면 validate라는 이름을 쓰는 것도 괜찮을 것 같습니다.  
관행상 이 이름을 써서 예외를 던지는 경우가 종종 있으니까요.  
```

## 4.1.4 호출하는 쪽에서 복구하고자 하는 오류에 대해 인지하도록 하라

```
public static Object parseKeepingOrder(Reader in) {
    try {
        return new JSONParser(DEFAULT_PERMISSIVE_MODE).parse(in, defaultReader.DEFAULT_ORDERED);
    } catch (Exception e) {
        return null;
    }
}

public static <T> T parseWithException(String in, Class<T> mapTo) throws ParseException {
    JSONParser p = new JSONParser(DEFAULT_PERMISSIVE_MODE);
    return p.parse(in, defaultReader.getMapper(mapTo));
}
```

> 1. Checked Exception, UnChecked Exception  
> 2. Checked Exception을 대하는 자세 : https://cheese10yun.github.io/checked-exception/
>    - 무책임하게 상위 메서드로 throw를 던지는 행위는 하지 않는 것이 좋습니다. 상위 메서드들의 책임이 그만큼 증가하기 때문입니다.  
>    - Checked Exception은 기본 트랜잭션에 속성에서는 rollback을 진행하지 않는 점도 알고 있어야 실수를 방지할 수 있습니다.  
>   
> 3. 코틀린이 CheckedException을 없앤 이유 : https://taes-k.github.io/2021/12/29/kotlin-checkedException/
>    - 만약 Exception을 캐치한다고 하더라도 적절하게 대응하기 힘든경우가 대부분이라 RuntimeException으로 rethrow처리하는 경우가 많습니다.
>    - 4~5개의 서로다른 CheckedExcpetion을 사용하는 하위 API를 호출하는 경우 Exception 체인이 기하급수적으로 증가할 수 있습니다.
>    - try catch 블록 내부에 코드를 배치하면, 컴파일러 최적화가 제한됨 (이펙티브 코틀린)
